### PR TITLE
Implement silent deploy & upgrade

### PR DESCRIPTION
**Pull request by wpouseele**
This PR implements the option to silently deploy and upgrade the AOE and allows as such for a more automated deployment or upgrade. I saw that the SilentDeploymentSettingsPath parameter was already defined but never implemented. This PR does just that.
At the same time, it implements a SQL password validation (only used with the silent deploy option at this time) to catch possible errors before deployment.

Fee free to provide additional remarks or suggest possible optimizations before merging.
One possible optimization is to generate a random SQL password instead of providing it in the deployment file and storing this password immediately in an Azure Key Vault. But I prefer to not over complicate the PR and would be willing to implement via a new PR if valuable.

### CODE REVIEW

**Comment by helderpinto** [comment]
Many thanks for your valuable and appreciated contribution, @wpouseele. Silent deployments were a pre-requisite for a GitHub Actions AOE deployment pipeline I hadn't had the time to implement so far. With your help, this will become a reality sooner and the community may implement their own upgrade pipelines at their will. 

I have some questions, though:

- Why are `SilentUpgrade`/`DoPartialUpgrade` mutually exclusive with `SilentDeploymentSettingsPath`? 1) I would expect a partial upgrade (which does not redeploy the ARM template) to be able to run silently if needed; and 2) if I turn the `SilentUpgrade` flag to true, I am expecting to have the `SilentDeploymentSettingsPath` filled in.
- It is not clear why we have `SilentUpgrade` and `silentDeploy` variables. What is the difference and why we need both?

I do agree with you, in that we should store the Azure SQL password in a Key Vault, but this can be added in a separate PR, to keep things simple at this moment.

**Comment by wpouseele** [comment]
Hi @helderpinto, 

- I made an effort to maximize reuse of code from the original source, which led me to avoid creating a separate file for SilentDeploymentSettings. Instead, I've integrated it with the existing `$deploymentOptions` and `$lastDeploymentStatePath`. Please note that the `SilentDeploymentSettingsPath` parameter is only relevant during the initial deployment. Thus, specifying `SilentDeploymentSettingsPath` alongside a `SilentUpgrade or DoPartialUpgrade` parameter is nonsensical since it holds no value at that juncture. My intention was to emphasize this through mutual exclusivity. The thrown error might help elucidate this distinction a little more. 😉
- The `SilentUpgrade` parameter is used to specify a silent upgrade from a perspective of a user running the script. Otherwise we don't have any way to indicate that we want the upgrade to be done silently (like without any further prompt asking to re-use the previous deployment settings).
- The `silentDeploy` variable is used within the script to bypass various prompts or selections when deploying silently and gets set automatically when specifying a SilentDeploymentSettingsPath parameter.

**Comment by helderpinto** [comment]
Hi, @wpouseele. Thanks for the clarifications. 

The `SilentDeploymentSettingsPath` parameter was initially intended to be used both at initial deployment and upgrade times. It would be great if users were also able to set up a continuous deployment pipeline based on your implementation. This would of course require removing the mutual exclusivity between `DoPartialUpgrade` and `SilentDeploymentSettingsPath` and renaming the `SilentUpgrade` parameter to a more generic term, e.g., `SilentMode`, or simply removing it and making the `SilentDeploymentSettingsPath` parameter an implicit choice for a silent mode execution. Both approaches are fine for me.

Allowing `SilentDeploymentSettingsPath` to be used both at initial deployment and upgrade times would require only a few changes in your code, maybe making it simpler, and would bring even more value to your work. Does it make sense?

**Comment by wpouseele** [comment]
Hi @helderpinto, sure makes total sense, assuming that the `SilentDeploymentSettingsPath` always overrules any last-deployment-state.json file.
Please find the needed changes in the additional commit.

**Comment by helderpinto** [comment]
Thanks for the update, @wpouseele! It looks good and thanks for taking care of the optional Benefits Usage workbooks deployment. I am going to merge your code. Thanks a lot for your contribution.

**Pull request merged**
